export const MEDICINE_FORMS = [
    "Tablet",
    "Capsule",
    "Injectibles",
    "Eye drops",
    "Otic drops",
    "Film-coated tablet",
    "Syrup",
    "Drops",
    "Suppository",
    "Vial",
    "Ampule",
    "Cream",
    "Ointment",
    "Gel",
    "Sachet",
    "Powder",
    "Effervescent tablet",
    "Patch",
    "Medical Supply",
];
