export const MEDICINE_FORMS = [
    "Tablet",
    "Capsule",
    "Injectibles",
    "Eye drops",
    "Otic drops",
    "Film-coated tablet",
    "Syrup",
    "Drops",
    "Suppository",
    "Vial",
    "Ampule",
    "Cream",
    "Ointment",
    "Gel",
    "Sachet",
    "Powder",
    "Effervescent tablet",
    "Patch",
    "Medical Supply",
    "Nebule",
    "Lotion",
    "Inhaler",
    "Bottle",
    "Gummies",
    "Suspension",
    "Chewable tablet",
    "Sublingual tablet",
    "Lozenge",
    "Nasal spray",
    "Nasal drops",
    "Solution",
    "Elixir",
    "Granules",
    "Enema",
    "Spray",
    "Pessary",
];
